export { default as Navbar } from './Navbar'
export { default as Header } from './Header'
export { default as Banner } from './Banner'
export { default as NewsBody } from './NewsBody'
export { default as Footer } from './Footer'
export { default as GoBack } from './GoBack'
